modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/thelegitdolt/bibliophile/issues"
license = "https://github.com/thelegitdolt/bibliophile/blob/main/LICENSE"

[[mods]]
modId = "bibliophile"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:book"
configBackground = "minecraft:textures/block/obsidian.png"
authors = "Dolt and Bagels"
credits = "Dolt and Bagels"
displayURL = "https://www.youtube.com/mods/caverns-and-chasms"
displayName = "Bibliophile"
description = '''
   MAKES ENCHANTING GOOD.
'''

[[dependencies.bibliophile]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.bibliophile]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.bibliophile]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"